import Head from 'next/head'
import {useRouter} from "next/router";
import LocaleSwitcher from "../components/LocaleSwitcher";
import Navigation from "../components/Navigation/Navigation";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import {useTranslation} from "next-i18next";
import Introduction from "../components/Intoduction/Introduction";


export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"]))
    }
  }
}


export default function Home() {
  const { t } = useTranslation()
  return (
    <>
      <Head>
        <title>Popov Alexander</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navigation sections={[
          {
            pathname: "/about",
            title: t("about")
          }
        ]}/>
        <LocaleSwitcher/>
      </header>

      <main>
        <Introduction />
      </main>

      <footer>

      </footer>
    </>
  )
}
